#!/usr/bin/env bash
# build-atmosphere-torrserve.sh — build the ATMOSphere-TorrServe APK and
# copy it into the parent ATMOSphere prebuilt-apps tree.
#
# Usage:
#     bash device/rockchip/atmosphere/torrserve/build-atmosphere-torrserve.sh
#
# Output:
#     device/rockchip/rk3588/prebuilt_apps/atmosphere-torrserve.apk
#
# Signing: debug-quality keystore generated on-demand. AOSP re-signs
# with the platform key at image-assembly time via
# LOCAL_CERTIFICATE := platform in prebuilt_apps/Android.mk.
#
# JDK: gradle 8.11.1 + AGP 8.10.1 are Java 21 compatible, so we use
# the AOSP-bundled jdk21 first, then fall back to a system jdk21, then
# last-resort the default java. (Unlike SmartTube which needs jdk17.)
#
# Fails loudly if any step breaks so scripts/build.sh can halt early.

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PARENT_ROOT="$(cd "$SCRIPT_DIR/../../../.." && pwd)"

cd "$SCRIPT_DIR"

echo "[ATMOSphere-TorrServe] build-atmosphere-torrserve.sh"
echo "  script dir: $SCRIPT_DIR"
echo "  parent:     $PARENT_ROOT"

# Ensure gradle wrappers are +x (some clones drop the bit).
for gw in ./gradlew; do
    [ -f "$gw" ] && chmod +x "$gw" 2>/dev/null || true
done

# Pick a JDK ≥ 21 (gradle 8.11.1 + AGP 8.10.1 require it).
_pick_jdk21() {
    if [ -n "${JAVA_HOME:-}" ] && [ -x "$JAVA_HOME/bin/java" ]; then
        _v=$("$JAVA_HOME/bin/java" -version 2>&1 | head -1)
        case "$_v" in
            *'"21'*|*'"22'*|*'"23'*|*'"24'*|*'"25'*)
                return 0 ;;
        esac
    fi
    for cand in \
        "$PARENT_ROOT/prebuilts/jdk/jdk21/linux-x86" \
        "$PARENT_ROOT/prebuilts/jdk/jdk21" \
        /usr/lib/jvm/java-21-openjdk \
        /usr/lib/jvm/java-21-openjdk-*.x86_64 \
        /usr/lib/jvm/jre-21-openjdk; do
        for actual in $cand; do
            if [ -x "$actual/bin/java" ]; then
                export JAVA_HOME="$actual"
                return 0
            fi
        done
    done
    echo "[ATMOSphere-TorrServe] WARNING: no JDK 21 found — gradle 8.11.1 may fail on older Java"
    return 1
}
_pick_jdk21 || true
if [ -n "${JAVA_HOME:-}" ]; then
    echo "[ATMOSphere-TorrServe] JAVA_HOME=$JAVA_HOME"
    "$JAVA_HOME/bin/java" -version 2>&1 | head -1
fi

# Provide keystore.properties if missing (debug-signed; AOSP re-signs).
if [ ! -f keystore.properties ]; then
    _DEBUG_KS="$HOME/.android/debug.keystore"
    if [ ! -f "$_DEBUG_KS" ]; then
        echo "[ATMOSphere-TorrServe] creating $_DEBUG_KS (fresh machine; standard debug passwords)"
        mkdir -p "$HOME/.android"
        keytool -genkey -v \
            -keystore "$_DEBUG_KS" \
            -storepass android -keypass android \
            -alias androiddebugkey \
            -dname "CN=Android Debug,O=Android,C=US" \
            -keyalg RSA -keysize 2048 -validity 10000 2>&1 | tail -2
    fi
    echo "[ATMOSphere-TorrServe] generating keystore.properties (debug-signed placeholder; AOSP re-signs)"
    cat > keystore.properties <<EOF
# Auto-generated by build-atmosphere-torrserve.sh — DO NOT COMMIT.
storeFile=$_DEBUG_KS
storePassword=android
keyAlias=androiddebugkey
keyPassword=android
EOF
fi

echo "[ATMOSphere-TorrServe] running: ./gradlew :app:assembleRelease"
bash ./gradlew :app:assembleRelease --no-daemon --console=plain

# Find the release APK.
APK_PATH=$(find app/build/outputs/apk/release -type f -name '*.apk' 2>/dev/null | head -1)
if [ -z "${APK_PATH:-}" ] || [ ! -f "$APK_PATH" ]; then
    echo "[ATMOSphere-TorrServe] ERROR: gradle reported success but no APK found under app/build/outputs/apk/release/"
    ls -la app/build/outputs/apk/release/ 2>&1 | head -10
    exit 2
fi
echo "[ATMOSphere-TorrServe] built APK: $APK_PATH"

DEST="$PARENT_ROOT/device/rockchip/rk3588/prebuilt_apps/atmosphere-torrserve.apk"
cp -f "$APK_PATH" "$DEST"
echo "[ATMOSphere-TorrServe] copied to: $DEST"
ls -lh "$DEST"

echo "[ATMOSphere-TorrServe] done. scripts/build.sh will pick this APK"
echo "  up via device/rockchip/rk3588/prebuilt_apps/Android.mk and re-"
echo "  sign with the platform key at system-image assembly."
